name: 🚀 Deploy the_vault config
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'config/the_vault/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload config/the_vault
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 2222
          uploads: |
            ./config/the_vault => ./config/the_vault
