name: 🚀 Deploy resourcepack

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: sudo apt-get install rclone

      - name: Configure rclone
        run: rclone config create target sftp host ${{ secrets.FTP_SERVER }} pass ${{ secrets.FTP_PASSWORD }} user ${{ secrets.FTP_USERNAME }} port 2222

      - name: Download resourcepack
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'SomeBody16/someresources'
          regex: true
          file: "someresources-*\\.zip"
          target: "someresources.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload resourcepack
        run: rclone copyto someresources.zip target:someresources.zip -v
