name: 🚀 Update dependencies

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    steps:
      - uses: actions/checkout@v3

      - name: Remove old dependencies
        run: |
          rm -rf mods/somepotter-*.jar

      - name: Get latest someresources download link
        id: get-latest-release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "SomeBody16/someresources"
          regex: true
          file: "someresources-.+\\.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update server.properties
        run: |
          # Remove old lines
          sed -i '/resource-pack=/d' server.properties
          sed -i '/resource-pack-sha1=/d' server.properties
          
          # Append new lines with the latest release info
          echo "resource-pack=${{ steps.get-latest-release.outputs.browser_download_url }}" >> server.properties
          echo "resource-pack-sha1=$GITHUB_SHA" >> server.properties

      - name: Update somepotter
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'SomeBody16/somepotter'
          regex: true
          file: "somepotter-.+\\.jar"
          target: "mods/"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update dependencies
          file_pattern: 'server.properties,mods/somepotter-*.jar'
