name: Update Modpack Version

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update bcc-common.toml
        run: |
          #!/bin/bash
          # Extract the current pack version and commit count
          current_version=$(grep 'modpackVersion = ' config/bcc-common.toml | sed -E 's/modpackVersion = "(.*)"/\1/')
          IFS='-' read -ra ADDR <<< "$current_version"
          pack_version="${ADDR[0]}"
          commit_count="${ADDR[1]}"
          
          # Increment the commit count
          new_commit_count=$((commit_count + 1))
          
          # Construct the new version
          new_version="${pack_version}-${new_commit_count}"
          
          # Update the file
          sed -i "s/modpackVersion = \"$current_version\"/modpackVersion = \"$new_version\"/" config/bcc-common.toml

      - name: Commit and Push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add config/bcc-common.toml
          git commit -m "Auto-update bcc-common.toml to $new_version" || echo "No changes to commit"
          git push || echo "No changes to push"
